### ISSUE TITLE
State of a default command execution interface support on xdg platforms

### ISSUE THREAD

**Issue by ManuelSchneid3r** [albertlauncher/albert-plugin-applications#1]
Running a command in a terminal from another app is a common usecase. Almost all terminals provide such a command execution interface (`-e`, `-x`, `--` or such). Clients of the desktop entry spec can [guess](https://github.com/albertlauncher/albert/blob/6783257df7e15dcfbae49d03023414b7c3692dbd/src/app/terminalprovider.cpp#L120-L150), but they cant know for sure since terminals break their CLI (no offense, I'd be happy if you all break it to go to `--`).

There is a [freedesktop spec proposal](https://gitlab.freedesktop.org/terminal-wg/specifications/-/merge_requests/3) that tries to standardize the way we configure a default terminal for command execution. It implicitly solves the above problem by requiring the dektop entry to provide this info.

To support it (X-)ExecArg has to be added to the desktop file ([like this](https://github.com/GNOME/gnome-terminal/blob/f1814cb7ecfe6a5cb4f629dcea56db0dec10a242/data/org.gnome.Terminal.desktop.in#L14), [the reference implementation respects both](https://github.com/Vladimir-csp/xdg-terminal-exec/blob/af3570e1af8691416e77171e7e29a03572d541c4/xdg-terminal-exec#L387)) and, as the proposal specifies currently, make sure there is TerminalEmulator in Categories. It has not yet been approved, therefore the `X-`.

The draft states that the default should be `-e` (because xterm once did). But I think we should not have a default at all because we have to support terminals not having such an interface and even if we do (which will break a lot of configs) we should use `--` (terminal authors should as well), because it is not a usual argument but instead changes the way the remainder of the command line is to be interpreted. So please be explicit.

As the author of a launcher I'd be even happy with the implicit changes to the lacking (we have the `Terminal` key, do we?) desktop entry spec. There is also a related [intentapp draft](https://gitlab.freedesktop.org/xdg/xdg-specs/-/merge_requests/45) and a [terminal intent](https://gitlab.freedesktop.org/xdg/xdg-specs/-/merge_requests/46). I dont have a favorite, but a [pragmatic opinion](https://lists.freedesktop.org/archives/xdg/2024-July/014746.html). This will help making Linux a better user experience and a less annoying developer experience.

Thank you

- [PR in xdg-specs](https://gitlab.freedesktop.org/xdg/xdg-specs/-/merge_requests/87)

---

- [ ] **Alacritty** https://github.com/alacritty/alacritty/pull/8139
- [ ] **BlackBox** https://gitlab.gnome.org/raggesilver/blackbox/-/issues/388
- [x] **Contour** https://github.com/contour-terminal/contour/issues/1570
- [ ] **Cool Retro Term** https://github.com/Swordfish90/cool-retro-term/issues/850
- [ ] **Deepin Terminal** https://github.com/orgs/linuxdeepin/discussions/9817
- [ ] **Elementary Terminal** https://github.com/elementary/terminal/issues/765
- [ ] **Foot Terminal** 
- [ ] **GNOME Console** https://gitlab.gnome.org/GNOME/console/-/issues/384
- [x] **GNOME Terminal** [Has it upstream](https://github.com/GNOME/gnome-terminal/blob/8cb21c53bea7ebd5e4e6cad34e6f072fadd61c66/data/org.gnome.Terminal.desktop.in#L14)
- [ ] **Kitty**
- [ ] **LXDE Terminal**
- [ ] **Mate Terminal**
- [ ] **QTerminal**
- [ ] **Roxterm**
- [ ] **Simple Terminal (ST)**
- [ ] **Terminator** https://github.com/gnome-terminator/terminator/issues/942
- [ ] **Terminology**
- [ ] **Termite**
- [ ] **Tilix**
- [ ] **UXterm**
- [ ] **URXVT**
- [ ] **Wezterm** https://github.com/wez/wezterm/issues/6008
- [ ] **XFCE Terminal**

**Comment by egnrse** [comment]
Motivated by your efforts a while ago. I looked into this thing again and came up with a list of what might be good next steps to bring this forward. I'm not sure how much time I have for this currently, but I though I would share my ideas for now. 

## TODO
(**citations!**)
- condense what has been said/discussed before (in one place)
- list (and ask) Terminals/DE supporting (wanting/willing to support it) (Gnome/KDE/terminals)
- compare proposal standards
- list of pros/cons (discussed, for DE,/Terminals)
- discuss more about how/names/locations with terminals/DEs/vlad/michael/? (condense this too)

compare DE/terminal by marketshare (see if big players would be on it, look what they currently do)


## Scope
(What should be covered by a standard solving this?)
- launch \*.desktop entries with `Terminal=True`
    - only handle arguments (eg. alacritty -e ...) or handle full launch commands?
    - how to set preference? (DE/Terminals/Users)
- include title/hold/...?


## LINKS
### Proposals
https://gitlab.freedesktop.org/terminal-wg/specifications/-/merge_requests/3 (xdg-terminal-exec)
https://gitlab.freedesktop.org/xdg/xdg-specs/-/merge_requests/87 (xdg-terminal-exec variant)
https://gitlab.freedesktop.org/xdg/xdg-specs/-/merge_requests/46 (Terminal Intent)
https://gitlab.freedesktop.org/xdg/xdg-specs/-/merge_requests/45 (intent-apps spec)
### Context
https://github.com/albertlauncher/albert-plugin-applications/issues/1 (updates/overview?)
https://github.com/Vladimir-csp/xdg-terminal-exec (implementation of xdg-terminal-exec)
### Also see
https://wiki.archlinux.org/title/Desktop_entries#Usage (programs DEs use that should support any standart)
https://gitlab.freedesktop.org/xdg/xdg-specs/-/issues/54#login-pane (discussion about app launching with Terminal=True)
https://lists.freedesktop.org/archives/xdg/2015-October/013583.html
https://lists.freedesktop.org/archives/xdg/2018-August/014072.html
https://wiki.archlinux.org/title/Category:Freedesktop.org


### How far are we?
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/4119 (Gnome and intends)
https://github.com/albertlauncher/albert-plugin-applications/issues/1 (updates/overview over terminals)
